# Generated by Django 5.2.7 on 2025-11-04 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restik', '0003_rename_reservation_datetime_reservation_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='waiter',
        ),
        migrations.AddField(
            model_name='customer',
            name='namex',
            field=models.CharField(default='Anonim', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
